version: "3.5"

services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
    command: bundle exec jekyll serve --watch -H 0.0.0.0 -t
